# Site settings
email:
baseurl: ""
paginate: 2
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: "MogGy-Page"
description: "Mi primer Citio web usando Jekyll"
url: ""
twitter_username:
default_img:

# Profile settings
name: "Edilberto Cañon"
profile_img: /assets/imges/sejuporo.jpg
profile: Estudiante de ingenieria de sistemas y computacion de la universidad nacional de comlombia
social:
 github: "https://github.com/MogGy94/MogGy94.github.io"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
